Hotfix EPL-749:Fix to resolve dependencies from nexus repo's.
etendosoftware/com.etendoerp.gradleplugin pull request #6
Opened 2023-07-04 12:52 UTC by LeandroCazorla15

2023-07-04 13:23 UTC, smfnicolasre requested changes
The format is not correct. Check spaces in if

2023-07-04 13:25 UTC, szapata commented
This commit is not a hotfix of EPL-749. Please correct this. is for EPL-740

2023-07-04 13:27 UTC, Matias-Bernal approved these changes

2023-07-04 14:17 UTC, Gremiger approved these changes

2023-07-04 16:58 UTC, juabaez approved these changes

2023-07-05 23:55 UTC, valeg-etendo approved these changes

2023-07-10 12:35 UTC, smfnicolasre approved these changes

2023-07-10 12:53 UTC, merged